"""
LLM-as-judge agent for evaluating financial QA answer quality.

Uses the cheapest available model (Gemini Flash Lite) to compare ground-truth
answers against LLM-generated answers, returning a per-pair boolean verdict.
"""

import asyncio

import openai
from loguru import logger
from pydantic import BaseModel
from pydantic_ai import Agent
from pydantic_ai.models.openrouter import OpenRouterModel, OpenRouterModelSettings, OpenRouterProviderConfig
from pydantic_ai.providers.openrouter import OpenRouterProvider

from app.agent import ModelName
from app.settings import get_settings

_JUDGE_MODEL = ModelName.GEMINI_3_1_FLASH_LITE
_INITIAL_RETRY_DELAY_SECONDS = 1.0

_SYSTEM_PROMPT = (
    "You are an answer-evaluation assistant for a financial question-answering benchmark.\n"
    "You will receive two ordered lists of the same length:\n"
    "  - GROUND TRUTH: the correct reference answers.\n"
    "  - PREDICTED: the answers generated by an LLM under evaluation.\n\n"
    "For each pair (ground_truth[i], predicted[i]), decide whether the predicted answer "
    "is semantically equivalent to the ground truth.\n\n"
    "Equivalence rules:\n"
    "  - Numeric formatting differences are correct: '3200' == '3200.0', '32%' == '32.00%'.\n"
    "  - Rounding to a reasonable number of decimal places is correct.\n"
    "  - Different but mathematically equal representations are correct.\n"
    "  - Answers with wrong values, wrong signs, or wrong units are incorrect.\n"
    "  - 'N/A' or missing answers are incorrect unless the ground truth is also 'N/A'.\n\n"
    "Return one boolean per pair, in the same order as the input lists. "
    "Do not add explanations or extra fields — only the structured output."
)


class JudgeResult(BaseModel):
    """Structured output returned by the judge agent."""

    results: list[bool]


def build_judge_agent() -> Agent[None, JudgeResult]:
    """Construct a pydantic-ai judge Agent hardcoded to the cheapest available model.

    The judge agent has no arithmetic tools — it only needs to compare strings.
    It always uses GEMINI_3_1_FLASH_LITE regardless of the model used for evaluation.

    Returns:
        A configured Agent that returns validated JudgeResult output.
    """
    settings = get_settings()
    max_retries = settings.max_retries

    openai_client = openai.AsyncOpenAI(
        api_key=settings.openrouter_api_key,
        base_url="https://openrouter.ai/api/v1",
        max_retries=max_retries,
    )
    model_settings = OpenRouterModelSettings(
        openrouter_provider=OpenRouterProviderConfig(ignore=["amazon-bedrock"]),
    )
    model = OpenRouterModel(
        _JUDGE_MODEL.value,
        provider=OpenRouterProvider(openai_client=openai_client),
        settings=model_settings,
    )
    return Agent(
        model,
        output_type=JudgeResult,
        instructions=_SYSTEM_PROMPT,
        retries=max_retries,
    )


def _format_judge_prompt(ground_truth: list[str], predicted: list[str]) -> str:
    """Format the two answer lists into a numbered prompt for the judge.

    Args:
        ground_truth: The reference answers.
        predicted: The LLM-generated answers to evaluate.

    Returns:
        A plain-text prompt listing each pair by index.
    """
    lines = ["GROUND TRUTH vs PREDICTED answer pairs:\n"]
    for i, (gt, pred) in enumerate(zip(ground_truth, predicted, strict=False), start=1):
        lines.append(f"{i}. Ground truth: {gt!r}  |  Predicted: {pred!r}")
    return "\n".join(lines)


async def _run_judge(agent: Agent[None, JudgeResult], prompt: str) -> JudgeResult:
    """Run the judge agent and return the result.

    Args:
        agent: The configured judge Agent.
        prompt: The formatted comparison prompt.

    Returns:
        JudgeResult with per-pair verdicts.
    """
    result = await agent.run(prompt)
    return result.output


async def get_judge_response(
    agent: Agent[None, JudgeResult],
    ground_truth: list[str],
    predicted: list[str],
    max_retries: int,
) -> JudgeResult:  # type: ignore[return]
    """Compare ground-truth and predicted answers using the judge agent.

    Formats the two lists into a single prompt and runs the judge agent.
    Retries on rate limit errors using exponential backoff (1s, 2s, 4s, …).

    Args:
        agent: The configured judge Agent.
        ground_truth: The reference answers.
        predicted: The LLM-generated answers to evaluate.
        max_retries: Maximum number of rate-limit retries before re-raising.

    Returns:
        JudgeResult with one boolean per answer pair.

    Raises:
        openai.RateLimitError: If the rate limit is still hit after all retries.
    """
    prompt = _format_judge_prompt(ground_truth, predicted)
    delay = _INITIAL_RETRY_DELAY_SECONDS

    for attempt in range(max_retries + 1):
        try:
            result = await _run_judge(agent, prompt)
        except openai.RateLimitError:
            if attempt == max_retries:
                raise
            logger.warning(f"Judge rate limit hit — retrying in {delay:.0f}s (attempt {attempt + 1}/{max_retries})")
            await asyncio.sleep(delay)
            delay *= 2
            continue

        return result
